$(document).ready(function(){
    $(".icon").click(function(){
        $(this).find(".design-image").toggle()
        $(this).find(".hidden-p").toggle() 
    })
    $(".column").hover(function(){
        $(this).find(".overlay-text").toggle()
    })
})
